#!/usr/bin/env python3
"""
T083: Latent Geometry Audit
============================
Question: Why does the empirical landscape compress into a productivity-
dominated 2D manifold (75.1% + 17.5%) while the generative simulations
consistently produce a much flatter geometry (~41.7%)?

Hypothesis: The latent geometry is not generated by local constraint
satisfaction alone. It requires ensemble-level properties — hierarchical
organization, resource competition, adaptive selection, multi-timescale
dynamics, or corridor occupancy pressure.

Design:
  Phase 0 — Baseline: T082 successful constellation (MC2+MC3+MC4+SP)
  Phase 1 — Hierarchical scaling: multi-level state organization
  Phase 2 — Resource competition: limited resource for state activity
  Phase 3 — Adaptive selection: learning which transitions to reinforce
  Phase 4 — Multi-timescale: slow context modulates fast transitions
  Phase 5 — Corridor pressure: feedback toward intermediate stability
  Phase 6 — Combined: all mechanisms together
  Phase 7 — Ablation: remove each mechanism from combined best

Target (from T078):
  - PC1 ~ 75.1%
  - Intrinsic dimensionality = 2
  - Fertile corridor with finite width
  - Generative metrics dominate PC1, stability metrics dominate PC2
"""

import csv, json, math, random
from pathlib import Path
from collections import Counter, defaultdict

import numpy as np

OUT = Path("/home/student/sgp_core_v2/sfh_sgp_ood_outputs")
random.seed(42)
np.random.seed(42)

TARGET_PC1 = 75.1
TARGET_INTRINSIC_DIM = 2


# ============================================================
# EXTENDED SYSTEM — can be augmented with geometry-generating mechanisms
# ============================================================

class ExtendedSystem:
    def __init__(self, params):
        self.params = params

        # Core parameters (same as T081/T082)
        self.base_n = params.get("base_n_states", 4)
        self.determinism = params.get("determinism", 0.7)
        self.connectivity = params.get("connectivity", 0.5)
        self.novelty_drive = params.get("novelty_drive", 0.3)
        self.boundary_strength = params.get("boundary_strength", 0.7)
        self.self_model_level = params.get("self_model_level", 0)
        self.sm_influence = params.get("self_model_influence", 0.0)

        # Geometry-generating mechanism parameters
        self.hierarchy_depth = params.get("hierarchy_depth", 0)
        self.hierarchy_influence = params.get("hierarchy_influence", 0.0)
        self.resource_limit = params.get("resource_limit", 0)
        self.resource_competition = params.get("resource_competition", 0.0)
        self.adaptation_rate = params.get("adaptation_rate", 0.0)
        self.context_sensitivity = params.get("context_sensitivity", 0.0)
        self.corridor_feedback = params.get("corridor_feedback", 0.0)

        # Initialize state space
        self.states = list(range(self.base_n))
        self.n_actual = self.base_n
        self.T = self._build_transition_matrix()

        # Hierarchical structure: assign levels to states
        if self.hierarchy_depth > 0:
            self.state_levels = [random.randint(0, self.hierarchy_depth - 1) for _ in range(self.base_n)]
        else:
            self.state_levels = [0] * self.base_n

        # Resource model
        if self.resource_limit > 0:
            self.resources = {s: random.uniform(0.5, 1.0) for s in range(self.base_n)}
            self.resource_max = {s: 1.0 for s in range(self.base_n)}
        else:
            self.resources = {}
            self.resource_max = {}

        # Adaptation: running statistics of transition outcomes
        if self.adaptation_rate > 0:
            self.transition_counts = Counter()
            self.transition_success = Counter()
        else:
            self.transition_counts = None
            self.transition_success = None

        # Multi-timescale: slow context state
        if self.context_sensitivity > 0:
            self.context_state = 0
            self.context_duration = 0
            self.context_history = [0]
        else:
            self.context_state = None
            self.context_duration = None
            self.context_history = None

        # Corridor feedback: running estimate of stability
        if self.corridor_feedback > 0:
            self.stability_history = []
        else:
            self.stability_history = None

        self.history = []
        self.visit_counts = Counter()
        self.state_ages = {}
        self.fixed_point_reached = False

    def _build_transition_matrix(self):
        n = self.base_n
        T = np.zeros((n, n))
        mask = np.random.random((n, n)) < self.connectivity
        np.fill_diagonal(mask, True)
        raw = np.random.random((n, n)) * mask
        if self.determinism > 0.8:
            for i in range(n):
                if np.random.random() < self.determinism:
                    raw[i] = 0
                    raw[i, np.random.randint(n)] = 1
        row_sums = raw.sum(axis=1)
        row_sums[row_sums == 0] = 1
        T = raw / row_sums[:, np.newaxis]
        return T

    def _hierarchical_modulation(self, current, candidate):
        """Modify transition probabilities based on hierarchical levels."""
        if self.hierarchy_depth <= 0 or self.hierarchy_influence <= 0:
            return candidate
        if current >= len(self.state_levels) or candidate >= len(self.state_levels):
            return candidate
        cur_level = self.state_levels[current]
        cand_level = self.state_levels[candidate]
        # Prefer same-level transitions; penalize cross-level jumps
        if cur_level == cand_level:
            return candidate  # no penalty
        if random.random() < self.hierarchy_influence:
            # Stay at current level — try to find a same-level state
            same_level = [s for s in range(self.n_actual) if s < len(self.state_levels)
                          and self.state_levels[s] == cur_level]
            if same_level:
                return random.choice(same_level)
            # If none, try adjacent level
            adj_level = cur_level + (1 if cand_level > cur_level else -1)
            adj = [s for s in range(self.n_actual) if s < len(self.state_levels)
                   and self.state_levels[s] == adj_level]
            if adj:
                return random.choice(adj)
        return candidate

    def _resource_check(self, state):
        """Check if state has sufficient resources; consume some."""
        if self.resource_limit <= 0 or self.resource_competition <= 0:
            return True
        if state not in self.resources:
            self.resources[state] = 0.5
            self.resource_max[state] = 1.0
        if self.resources[state] <= 0:
            return False
        self.resources[state] -= random.uniform(0, self.resource_competition * 0.1)
        return True

    def _replenish_resources(self):
        """Let resources recover gradually."""
        if self.resource_limit <= 0 or self.resource_competition <= 0:
            return
        for s in self.resources:
            self.resources[s] = min(self.resource_max[s],
                                    self.resources[s] + random.uniform(0, self.resource_competition * 0.05))

    def _adapt_transition(self, from_state, to_state, outcome):
        """Adapt transition probabilities based on outcome quality."""
        if self.adaptation_rate <= 0:
            return
        if self.transition_counts is None:
            return
        key = (from_state, to_state)
        self.transition_counts[key] += 1
        self.transition_success[key] = self.transition_success.get(key, 0) + (1 if outcome > 0.5 else 0)

    def _context_step(self):
        """Update slow context state."""
        if self.context_sensitivity <= 0:
            return
        self.context_duration += 1
        if self.context_duration > random.randint(10, 30):
            self.context_state = random.randint(0, max(1, self.hierarchy_depth - 1))
            self.context_duration = 0
        self.context_history.append(self.context_state)

    def _corridor_adjustment(self, current_cycle_length):
        """Adjust dynamics to stay near intermediate stability."""
        if self.corridor_feedback <= 0:
            return 0.0
        if current_cycle_length <= 1:
            # Too rigid — increase novelty
            return +self.corridor_feedback * 0.3
        elif current_cycle_length >= 10:
            # Too chaotic — decrease novelty
            return -self.corridor_feedback * 0.3
        # In corridor — no adjustment
        return 0.0

    def step(self):
        if not self.history:
            self.history.append(0)
            self.visit_counts[0] += 1
            self.state_ages[0] = 0
            self._context_step()
            self._replenish_resources()
            return 0

        current = self.history[-1]

        # Multi-timescale: context modulates transitions
        effective_T = self.T.copy()
        if self.context_sensitivity > 0 and self.context_state > 0:
            context_level = self.context_state
            # Bias transitions toward or away from certain levels
            for i in range(min(self.n_actual, len(effective_T))):
                for j in range(min(self.n_actual, len(effective_T[i]))):
                    if j < len(self.state_levels) and self.state_levels[j] == context_level:
                        effective_T[i, j] *= (1.0 + self.context_sensitivity * 0.5)
            # Renormalize
            row_sums = effective_T.sum(axis=1)
            row_sums[row_sums == 0] = 1
            effective_T = effective_T / row_sums[:, np.newaxis]

        # Self-modeling
        if self.self_model_level > 0 and np.random.random() < self.sm_influence:
            modulated = self._self_model_modulated(current)
            if modulated != current:
                current = modulated

        # Corridor feedback: adjust effective novelty drive
        cycle_len = self._find_recent_cycle_length()
        drive_adjust = self._corridor_adjustment(cycle_len)
        effective_novelty = max(0.0, min(1.0, self.novelty_drive + drive_adjust))

        # Novelty generation
        if np.random.random() < effective_novelty:
            new_state = self._generate_new_state()
            if new_state is not None:
                self.history.append(new_state)
                self.visit_counts[new_state] += 1
                self.state_ages[new_state] = 0
                if new_state >= len(self.state_levels):
                    if self.hierarchy_depth > 0:
                        self.state_levels.append(random.randint(0, self.hierarchy_depth - 1))
                        self.state_levels[self.base_n - 1] = random.randint(0, self.hierarchy_depth - 1)
                    else:
                        self.state_levels.append(0)
                if self.resource_limit > 0:
                    self.resources[new_state] = 0.8
                    self.resource_max[new_state] = 1.0
                self._context_step()
                self._replenish_resources()
                return new_state

        # Normal transition
        if current < len(effective_T) and self.n_actual > 0:
            next_state = np.random.choice(self.n_actual, p=effective_T[current])
        else:
            next_state = 0

        # Hierarchical modulation
        if self.hierarchy_depth > 0:
            next_state = self._hierarchical_modulation(current, next_state)

        # Resource check
        if self.resource_limit > 0:
            if not self._resource_check(next_state):
                # State exhausted — try another
                candidates = [s for s in range(self.n_actual) if s in self.resources and self.resources[s] > 0]
                if candidates:
                    next_state = random.choice(candidates)

        self.history.append(next_state)
        self.visit_counts[next_state] += 1

        # Adaptive learning
        if self.adaptation_rate > 0:
            outcome = random.random()  # simulated outcome
            self._adapt_transition(current, next_state, outcome)

        self._context_step()
        self._replenish_resources()
        return next_state

    def _self_model_modulated(self, current):
        if self.self_model_level == 1:
            recent = self.history[-min(3, len(self.history)):]
            if len(set(recent)) == 1:
                return random.choice(range(self.n_actual))
        elif self.self_model_level == 2:
            if self.visit_counts[current] > max(self.n_actual, 3):
                candidates = [s for s in range(self.n_actual) if self.visit_counts[s] < self.visit_counts[current]]
                if candidates:
                    return random.choice(candidates)
        elif self.self_model_level >= 3:
            if self._detect_cycle():
                candidates = [s for s in range(self.n_actual) if self.visit_counts.get(s, 0) < 2]
                if candidates:
                    return random.choice(candidates)
        return current

    def _detect_cycle(self):
        if len(self.history) < 6:
            return False
        recent = self.history[-6:]
        return len(recent) == 6 and len(set(recent)) <= 3

    def _find_recent_cycle_length(self):
        h = self.history
        if len(h) < 4:
            return 0
        recent = h[-20:]
        seen = {}
        for i, s in enumerate(recent):
            if s in seen:
                return i - seen[s]
            seen[s] = i
        return len(set(h))

    def _generate_new_state(self):
        if self.boundary_strength > 0.9:
            return None
        expansion_ok = np.random.random() < (1.0 - self.boundary_strength) * 0.3
        if not expansion_ok:
            return None
        new_id = self.n_actual
        self.n_actual += 1
        self.states.append(new_id)
        old_T = self.T
        new_T = np.zeros((self.n_actual, self.n_actual))
        new_T[:old_T.shape[0], :old_T.shape[0]] = old_T
        for i in range(self.n_actual):
            conn = np.random.random(self.n_actual) < self.connectivity
            conn[i] = True
            raw = np.random.random(self.n_actual) * conn
            if raw.sum() == 0:
                raw[i] = 1
            new_T[i] = raw / raw.sum()
        self.T = new_T
        self.visit_counts[new_id] = 0
        self.state_ages[new_id] = 0
        if new_id >= len(self.state_levels):
            if self.hierarchy_depth > 0:
                self.state_levels.append(random.randint(0, self.hierarchy_depth - 1))
            else:
                self.state_levels.append(0)
        return new_id

    def run(self, steps=200):
        for _ in range(steps):
            self.step()
        return self._compute_metrics()

    def _compute_metrics(self):
        h = self.history
        n = len(h)
        if n == 0:
            return defaultdict(float)
        unique_ratio = len(set(h)) / max(1, self.n_actual)
        cycle_length = self._find_recent_cycle_length()
        convergence = 1.0 if cycle_length <= 1 else (1.0 / cycle_length if cycle_length > 0 else 0)
        entropy = self._compute_entropy()
        self_correlation = self._compute_self_correlation()
        trans_div = self._compute_transition_diversity()
        sm_ratio = self.self_model_level / 3.0
        sm_impact = self.sm_influence
        return {
            "unique_ratio": unique_ratio,
            "cycle_length": cycle_length,
            "convergence": convergence,
            "entropy": entropy,
            "self_correlation": self_correlation,
            "transition_diversity": trans_div,
            "sm_ratio": sm_ratio,
            "sm_impact": sm_impact,
            "n_states_actual": self.n_actual,
            "total_steps": n,
            "state_expansions": self.n_actual - self.base_n,
        }

    def _find_cycle_length(self):
        h = self.history
        if len(h) < 4:
            return len(set(h))
        recent = h[-20:]
        seen = {}
        for i, s in enumerate(recent):
            if s in seen:
                return i - seen[s]
            seen[s] = i
        return len(set(h))

    def _compute_entropy(self):
        if not self.history:
            return 0
        counts = Counter(self.history)
        total = len(self.history)
        ent = 0
        for c in counts.values():
            p = c / total
            if p > 0:
                ent -= p * math.log2(p)
        return ent / max(1, math.log2(len(counts)))

    def _compute_self_correlation(self):
        h = self.history
        if len(h) < 4:
            return 0
        lag = min(3, len(h) // 2)
        matches = sum(1 for i in range(len(h) - lag) if h[i] == h[i + lag])
        return matches / (len(h) - lag)

    def _compute_transition_diversity(self):
        trans = list(zip(self.history[:-1], self.history[1:]))
        if not trans:
            return 0
        return len(set(trans)) / max(1, len(trans))


# ============================================================
# CONSTRAINT SCORING (same as T082)
# ============================================================

def score_mc2(metrics):
    uniq = metrics.get("unique_ratio", 0)
    expan = metrics.get("state_expansions", 0)
    entropy = metrics.get("entropy", 0)
    trans_div = metrics.get("transition_diversity", 0)
    score = (uniq * 0.3 + min(1.0, expan / 5) * 0.25 + entropy * 0.25 + trans_div * 0.2)
    return min(1.0, score)

def score_mc3(metrics):
    cycle = metrics.get("cycle_length", 0)
    convergence = metrics.get("convergence", 0)
    sm = metrics.get("sm_ratio", 0)
    sc = metrics.get("self_correlation", 0)
    if cycle == 0:
        freedom = 0.0
    elif cycle == 1:
        freedom = 0.0
    elif cycle <= 3:
        freedom = 0.3
    elif cycle <= 6:
        freedom = 0.7
    elif cycle <= 10:
        freedom = 0.5
    else:
        freedom = 0.2
    rigidity = convergence
    balance = 1.0 - abs(freedom - rigidity)
    balance_weighted = balance * 0.5 + (1.0 - abs(convergence - 0.5)) * 0.3 + sm * 0.2
    return min(1.0, balance_weighted)

def score_mc4(metrics):
    sm_r = metrics.get("sm_ratio", 0)
    sm_i = metrics.get("sm_impact", 0)
    sc = metrics.get("self_correlation", 0)
    return min(1.0, sm_r * 0.4 + sm_i * 0.3 + sc * 0.3)

def score_sp(metrics):
    uniq = metrics.get("unique_ratio", 0)
    sc = metrics.get("self_correlation", 0)
    cycle = metrics.get("cycle_length", 0)
    convergence = metrics.get("convergence", 0)
    uniq_score = 1.0 - abs(uniq - 0.5) * 1.5
    if cycle == 0:
        cycle_score = 0.0
    elif cycle <= 3:
        cycle_score = 0.8
    elif cycle <= 6:
        cycle_score = 1.0
    elif cycle <= 10:
        cycle_score = 0.5
    else:
        cycle_score = 0.2
    score = uniq_score * 0.3 + sc * 0.3 + cycle_score * 0.2 + (1.0 - abs(convergence - 0.6)) * 0.2
    return min(1.0, max(0.0, score))


# ============================================================
# SUBSTRATE ASSUMPTION MEASUREMENT
# ============================================================

def measure_oc2(metrics, system):
    if system.n_actual < 2:
        return 0.0
    trans_sets = [set(np.where(row > 0.01)[0].tolist()) for row in system.T]
    unique_trans = len(set(tuple(sorted(t)) for t in trans_sets))
    return min(1.0, unique_trans / max(1, system.n_actual))

def measure_oc1(metrics, system):
    h = system.history
    if len(h) < 10:
        return 0.0
    recent = h[-20:]
    recurrence = len(set(recent)) / max(1, len(recent))
    return 1.0 - recurrence

def measure_cd1(metrics, system):
    if len(system.history) < 5:
        return 0.0
    raw_determinism = system.determinism
    trans = list(zip(system.history[:-1], system.history[1:]))
    if not trans:
        return 0.0
    state_outcomes = defaultdict(list)
    for s, ns in trans:
        state_outcomes[s].append(ns)
    consistency = 0
    for s, outs in state_outcomes.items():
        if len(outs) >= 2:
            most_common = Counter(outs).most_common(1)[0][1]
            consistency += most_common / len(outs)
    consistency /= max(1, len(state_outcomes))
    return raw_determinism * 0.4 + consistency * 0.6

def measure_ic1(metrics, system):
    if system.n_actual < 2:
        return 0.0
    trans = list(zip(system.history[:-1], system.history[1:]))
    if not trans:
        return 0.0
    state_outcomes = defaultdict(set)
    for s, ns in trans:
        state_outcomes[s].add(ns)
    future_divergence = 0
    for s, outcomes in state_outcomes.items():
        future_divergence += len(outcomes) / max(1, system.n_actual)
    future_divergence /= max(1, len(state_outcomes))
    return min(1.0, future_divergence * 1.5)

def measure_is1(metrics, system):
    h = system.history
    if len(h) < 10:
        return 0.0
    blocks = [h[i:i+5] for i in range(0, len(h)-4, 5)]
    if len(blocks) < 2:
        return 0.0
    changes = sum(1 for i in range(1, len(blocks)) if set(blocks[i]) != set(blocks[i-1]))
    return min(1.0, changes / max(1, len(blocks) - 1))

def measure_is2(metrics, system):
    h = system.history
    if len(h) < 5:
        return 0.0
    recent = h[-10:]
    if len(set(recent)) <= 2:
        return 1.0
    return min(0.5, 5.0 / len(set(recent)))

def measure_cd2(metrics, system):
    sm = system.self_model_level
    sm_i = system.sm_influence
    sc = metrics.get("self_correlation", 0)
    cycle = metrics.get("cycle_length", 0)
    score = (min(1.0, sm / 2) * 0.4 + sm_i * 0.3 +
             min(1.0, sc * 1.5) * 0.15 +
             (1.0 if cycle > 2 else 0.0) * 0.15)
    return min(1.0, score)

def measure_ec1(metrics, system):
    sm = system.self_model_level
    sm_i = system.sm_influence
    sc = metrics.get("self_correlation", 0)
    return min(1.0, (sm / 3) * 0.5 + sm_i * 0.3 + sc * 0.2)

def measure_sr1(metrics, system):
    sm = system.self_model_level
    sm_i = system.sm_influence
    cycle = metrics.get("cycle_length", 0)
    sc = metrics.get("self_correlation", 0)
    if sm < 2:
        return sm * 0.3
    return min(1.0, (sm / 3) * 0.3 + sm_i * 0.3 + (1.0 if cycle > 1 else 0.0) * 0.2 + sc * 0.2)


# ============================================================
# VIABILITY & FERTILITY
# ============================================================

def compute_coherence(metrics, system, em):
    det = system.determinism
    sc = metrics.get("self_correlation", 0)
    oc2 = em.get("OC2", 0)
    return min(1.0, (det * 0.3 + sc * 0.3 + oc2 * 0.4))

def compute_persistence(metrics, system, em):
    conv = metrics.get("convergence", 0)
    cycle = metrics.get("cycle_length", 0)
    oc1 = em.get("OC1", 0)
    stab = (1.0 if cycle <= 5 else 0.5 if cycle <= 10 else 0.2) * 0.4
    return min(1.0, stab + conv * 0.3 + oc1 * 0.3)

def compute_generativity(metrics, system, em):
    mc2 = score_mc2(metrics)
    expan = metrics.get("state_expansions", 0)
    trans_div = metrics.get("transition_diversity", 0)
    ic1 = em.get("IC1", 0)
    return min(1.0, mc2 * 0.4 + min(1.0, expan / 3) * 0.2 + trans_div * 0.2 + ic1 * 0.2)

def compute_recoverability(metrics, system, em):
    conv = metrics.get("convergence", 0)
    cycle = metrics.get("cycle_length", 0)
    sc = metrics.get("self_correlation", 0)
    cd1 = em.get("CD1", 0)
    recover = (1.0 if 2 <= cycle <= 6 else 0.5 if cycle > 0 else 0.0) * 0.4
    return min(1.0, recover + conv * 0.2 + sc * 0.2 + cd1 * 0.2)

def compute_self_modeling(metrics, system, em):
    ec1 = em.get("EC1", 0)
    sr1 = em.get("SR1", 0)
    cd2 = em.get("CD2", 0)
    return min(1.0, ec1 * 0.4 + sr1 * 0.3 + cd2 * 0.3)

def compute_novelty_production(metrics, system, em):
    uniq = metrics.get("unique_ratio", 0)
    expan = metrics.get("state_expansions", 0)
    entropy = metrics.get("entropy", 0)
    return min(1.0, uniq * 0.4 + min(1.0, expan / 4) * 0.3 + entropy * 0.3)

def compute_structural_richness(metrics, system, em):
    trans_div = metrics.get("transition_diversity", 0)
    n = system.n_actual
    is1 = em.get("IS1", 0)
    return min(1.0, trans_div * 0.4 + min(1.0, n / 8) * 0.3 + is1 * 0.3)

def compute_recombination(metrics, system, em):
    sc = metrics.get("self_correlation", 0)
    cd2 = em.get("CD2", 0)
    cycle = metrics.get("cycle_length", 0)
    trans_div = metrics.get("transition_diversity", 0)
    return min(1.0, sc * 0.3 + cd2 * 0.3 + (1.0 if cycle >= 3 else cycle / 3) * 0.2 + trans_div * 0.2)

def compute_recursive_depth(metrics, system, em):
    sm = system.self_model_level
    sr1 = em.get("SR1", 0)
    ec1 = em.get("EC1", 0)
    cd2 = em.get("CD2", 0)
    return min(1.0, (sm / 3) * 0.4 + sr1 * 0.3 + ec1 * 0.15 + cd2 * 0.15)

def compute_open_endedness(metrics, system, em):
    mc2 = score_mc2(metrics)
    expan = metrics.get("state_expansions", 0)
    unique = metrics.get("unique_ratio", 0)
    is1 = em.get("IS1", 0)
    return min(1.0, mc2 * 0.3 + min(1.0, expan / 3) * 0.3 + unique * 0.2 + is1 * 0.2)


# ============================================================
# MECHANISM DETECTION
# ============================================================

def detect_mechanisms(metrics, system):
    h = system.history
    sm = system.self_model_level
    n = system.n_actual
    cycle = metrics.get("cycle_length", 0)
    conv = metrics.get("convergence", 0)
    det = system.determinism
    sm_i = system.sm_influence
    sc = metrics.get("self_correlation", 0)
    uniq = metrics.get("unique_ratio", 0)
    entropy = metrics.get("entropy", 0)
    m01 = 1.0 if (sm < 2 and n >= 4) else (0.5 if sm < 2 else 0.0)
    m02 = 1.0 if (cycle == 1 and conv > 0.8) else (0.5 if cycle <= 2 else 0.0)
    m03 = det * 0.7 + (1.0 if system.novelty_drive < 0.2 else 0.0) * 0.3
    m04 = min(1.0, sm_i * 0.5 + sc * 0.5)
    m05 = max(0.0, 1.0 - uniq * 0.5 - entropy * 0.5)
    m06 = 1.0 if (conv > 0.9 and cycle <= 2 and sc > 0.8) else (0.5 if cycle <= 3 else 0.0)
    if len(h) < 10:
        m07 = 0.0
    else:
        recent = h[-10:]
        m07 = 0.8 if len(set(recent)) == len(recent) else 0.0
    m08 = 1.0 if (sm >= 2 and cycle > 2 and sc > 0.6) else (0.5 if cycle > 2 else 0.0)
    return {"M01": m01, "M02": m02, "M03": m03, "M04": m04,
            "M05": m05, "M06": m06, "M07": m07, "M08": m08}


# ============================================================
# PHASE DEFINITIONS — which geometry mechanism to activate
# ============================================================

PHASE_DEFS = [
    {
        "name": "baseline",
        "label": "Baseline (no geometry mechanism)",
        "mechanism": "none",
        "mech_params": {},
    },
    {
        "name": "hierarchy",
        "label": "Hierarchical scaling",
        "mechanism": "hierarchy",
        "mech_params": {"hierarchy_depth": 3, "hierarchy_influence": 0.4},
    },
    {
        "name": "resource",
        "label": "Resource competition",
        "mechanism": "resource",
        "mech_params": {"resource_limit": 10, "resource_competition": 0.5},
    },
    {
        "name": "adaptation",
        "label": "Adaptive selection",
        "mechanism": "adaptation",
        "mech_params": {"adaptation_rate": 0.3},
    },
    {
        "name": "timescale",
        "label": "Multi-timescale",
        "mechanism": "timescale",
        "mech_params": {"context_sensitivity": 0.5},
    },
    {
        "name": "corridor",
        "label": "Corridor pressure",
        "mechanism": "corridor",
        "mech_params": {"corridor_feedback": 0.4},
    },
    {
        "name": "combined",
        "label": "Combined (all mechanisms)",
        "mechanism": "combined",
        "mech_params": {
            "hierarchy_depth": 3, "hierarchy_influence": 0.3,
            "resource_limit": 10, "resource_competition": 0.4,
            "adaptation_rate": 0.2,
            "context_sensitivity": 0.4,
            "corridor_feedback": 0.3,
        },
    },
]

ASS_IDS = ["OC2", "OC1", "CD1", "IC1", "IS1", "IS2", "CD2", "EC1", "SR1"]
MECH_IDS = ["M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08"]


def assay_system(params):
    system = ExtendedSystem(params)
    metrics = system.run(200)

    mc2 = score_mc2(metrics)
    mc3 = score_mc3(metrics)
    mc4 = score_mc4(metrics)
    sp = score_sp(metrics)

    em = {a: f(metrics, system) for a, f in zip(
        ASS_IDS,
        [measure_oc2, measure_oc1, measure_cd1, measure_ic1,
         measure_is1, measure_is2, measure_cd2, measure_ec1, measure_sr1]
    )}
    mechs = detect_mechanisms(metrics, system)
    viability = {
        "C": compute_coherence(metrics, system, em),
        "P": compute_persistence(metrics, system, em),
        "G": compute_generativity(metrics, system, em),
        "R": compute_recoverability(metrics, system, em),
        "S": compute_self_modeling(metrics, system, em),
    }
    fertility = {
        "SR": compute_structural_richness(metrics, system, em),
        "NP": compute_novelty_production(metrics, system, em),
        "RC": compute_recombination(metrics, system, em),
        "RD": compute_recursive_depth(metrics, system, em),
        "OE": compute_open_endedness(metrics, system, em),
    }
    viability_threshold = (
        viability["C"] >= 0.75 and
        viability["P"] >= 0.65 and
        viability["G"] >= 0.40
    )
    fertile_signature = (
        viability_threshold and
        fertility["SR"] >= 0.5 and
        fertility["NP"] >= 0.5 and
        fertility["RC"] >= 0.5
    )
    stability = (viability["C"] + viability["P"] + viability["R"]) / 3
    fert_index = (fertility["SR"] + fertility["NP"] + fertility["RC"] +
                  fertility["RD"] + fertility["OE"]) / 5

    return {
        "params": params,
        "metrics": metrics,
        "mc2": mc2, "mc3": mc3, "mc4": mc4, "sp": sp,
        "em": em, "mechs": mechs,
        "viability": viability, "fertility": fertility,
        "viable": viability_threshold,
        "fertile": fertile_signature,
        "stability": stability,
        "fertility_index": fert_index,
    }


def build_params(base_params, mech_name, mech_params):
    p = dict(base_params)
    if mech_name == "none":
        pass
    elif mech_name == "hierarchy":
        p["hierarchy_depth"] = mech_params.get("hierarchy_depth", 2)
        p["hierarchy_influence"] = mech_params.get("hierarchy_influence", 0.3)
    elif mech_name == "resource":
        p["resource_limit"] = mech_params.get("resource_limit", 10)
        p["resource_competition"] = mech_params.get("resource_competition", 0.3)
    elif mech_name == "adaptation":
        p["adaptation_rate"] = mech_params.get("adaptation_rate", 0.2)
    elif mech_name == "timescale":
        p["context_sensitivity"] = mech_params.get("context_sensitivity", 0.3)
    elif mech_name == "corridor":
        p["corridor_feedback"] = mech_params.get("corridor_feedback", 0.3)
    elif mech_name == "combined":
        p.update(mech_params)
    return p


def run_pca(results):
    """Run PCA on viability+fertility metrics. Returns explained variance and loadings."""
    metric_names = ["C", "P", "G", "R", "S", "SR", "NP", "RC", "RD", "OE"]
    X = np.array([[r["viability"].get(m, r["fertility"].get(m, 0)) for m in metric_names] for r in results])
    X_centered = X - X.mean(axis=0)
    U, s, Vt = np.linalg.svd(X_centered, full_matrices=False)
    eigvals = s ** 2
    explained = eigvals / eigvals.sum() * 100
    cumulative = np.cumsum(explained)
    intrinsic_dim = int(np.searchsorted(cumulative, 90) + 1)
    # Loadings: correlation of each metric with PCs
    loadings = Vt.T
    return {
        "explained": [round(float(e), 2) for e in explained],
        "cumulative": [round(float(c), 2) for c in cumulative],
        "pc1_pct": round(float(explained[0]), 1),
        "pc2_pct": round(float(explained[1]), 1) if len(explained) > 1 else 0,
        "intrinsic_dim": int(intrinsic_dim),
        "n_components": len(explained),
        "loadings_pc1": [round(float(l), 3) for l in loadings[:, 0]],
        "loadings_pc2": [round(float(l), 3) for l in loadings[:, 1]],
        "metric_names": metric_names,
    }


def run_corridor_analysis(results):
    """Analyze fertile corridor geometry."""
    viable = [r for r in results if r["viable"]]
    if len(viable) < 10:
        return {"corridor_detected": None, "edge_of_chaos_pct": None, "n_viable": len(viable)}
    stabilities = np.array([r["stability"] for r in viable])
    fertilities = np.array([r["fertility_index"] for r in viable])
    n_bins = 5
    bin_edges = np.linspace(stabilities.min(), stabilities.max(), n_bins + 1)
    bin_max_fert = []
    for i in range(n_bins):
        mask = (stabilities >= bin_edges[i]) & (stabilities <= bin_edges[i + 1]) if i == n_bins - 1 else \
               (stabilities >= bin_edges[i]) & (stabilities < bin_edges[i + 1])
        bin_max_fert.append(float(np.max(fertilities[mask])) if mask.sum() > 0 else 0.0)
    mid_idx = n_bins // 2
    corridor_detected = bool(bin_max_fert[mid_idx] >= 0.7)
    med_stab = float(np.median(stabilities))
    med_fert = float(np.median(fertilities))
    quads = {"HS/HF": 0, "HS/LF": 0, "LS/HF": 0, "LS/LF": 0}
    for s, f in zip(stabilities, fertilities):
        if s >= med_stab and f >= med_fert:
            quads["HS/HF"] += 1
        elif s >= med_stab:
            quads["HS/LF"] += 1
        elif f >= med_fert:
            quads["LS/HF"] += 1
        else:
            quads["LS/LF"] += 1
    total_q = sum(quads.values())
    edge_of_chaos_pct = round(quads["LS/HF"] / total_q * 100, 1) if total_q else None
    return {
        "corridor_detected": corridor_detected,
        "edge_of_chaos_pct": edge_of_chaos_pct,
        "n_viable": len(viable),
        "stability_range": [round(float(stabilities.min()), 3), round(float(stabilities.max()), 3)],
        "med_stability": float(np.median(stabilities)),
        "quads": quads,
    }


# ============================================================
# MAIN
# ============================================================

print("=" * 72)
print("T083: LATENT GEOMETRY AUDIT")
print("=" * 72)

# Generate diverse parameter grid
print("\nGenerating parameter grid...")
base_params_list = []
for det in [0.2, 0.4, 0.6, 0.8, 0.95]:
    for conn in [0.3, 0.5, 0.7, 0.9]:
        for sm_level in [0, 1, 2, 3]:
            for sm_inf in [0.0, 0.3, 0.6]:
                for nov in [0.1, 0.2, 0.3, 0.5]:
                    for boundary in [0.3, 0.5, 0.7, 0.9]:
                        base_params_list.append({
                            "base_n_states": random.choice([3, 4, 5, 6]),
                            "determinism": det,
                            "connectivity": conn,
                            "novelty_drive": nov,
                            "boundary_strength": boundary,
                            "self_model_level": sm_level,
                            "self_model_influence": sm_inf,
                        })
random.shuffle(base_params_list)
base_params_list = base_params_list[:300]
print(f"  {len(base_params_list)} base configurations")

all_phase_results = []

for pdef in PHASE_DEFS:
    params_list = [build_params(bp, pdef["mechanism"], pdef["mech_params"]) for bp in base_params_list]
    results = []
    print(f"\n--- {pdef['label']} ---")
    for i, params in enumerate(params_list):
        r = assay_system(params)
        results.append(r)
        if (i + 1) % 100 == 0:
            print(f"  Ran {i+1}/{len(params_list)}...")
    print(f"  Complete: {len(results)} systems")

    # MC constraints for grouping
    def sat_all(r):
        return r["mc2"] >= 0.5 and r["mc3"] >= 0.5 and r["mc4"] >= 0.5 and r["sp"] >= 0.5
    def sat_none(r):
        return r["mc2"] < 0.5 and r["mc3"] < 0.5 and r["mc4"] < 0.5 and r["sp"] < 0.5

    all_sat = [r for r in results if sat_all(r)]
    none_sat = [r for r in results if sat_none(r)]

    # Assumption emergence
    ass_emergent = []
    for aid in ASS_IDS:
        a_mean = np.mean([r["em"][aid] for r in all_sat]) if all_sat else 0
        n_mean = np.mean([r["em"][aid] for r in none_sat]) if none_sat else 0
        if a_mean - n_mean >= 0.2:
            ass_emergent.append(aid)

    # Mechanism emergence
    mech_emergent = []
    for mid in MECH_IDS:
        a_mean = np.mean([r["mechs"][mid] for r in all_sat]) if all_sat else 0
        n_mean = np.mean([r["mechs"][mid] for r in none_sat]) if none_sat else 0
        if a_mean - n_mean >= 0.15:
            mech_emergent.append(mid)

    # Viability basin
    viable_all = sum(1 for r in all_sat if r["viable"])
    viable_none = sum(1 for r in none_sat if r["viable"])
    basin = (viable_all / max(1, len(all_sat))) > (viable_none / max(1, len(none_sat))) * 2 \
        if none_sat else None

    # PCA
    pca = run_pca(results)

    # Corridor
    corridor = run_corridor_analysis(results)

    phase_result = {
        "label": pdef["label"],
        "name": pdef["name"],
        "n_all": len(all_sat),
        "n_none": len(none_sat),
        "n_systems": len(results),
        "assumptions": {
            "n_emergent": len(ass_emergent),
            "emergent_list": ass_emergent,
        },
        "mechanisms": {
            "n_emergent": len(mech_emergent),
            "emergent_list": mech_emergent,
        },
        "viability_basin": basin,
        "pca": pca,
        "corridor": corridor,
    }
    all_phase_results.append(phase_result)

    print(f"  All-sat: {len(all_sat)}, None-sat: {len(none_sat)}")
    print(f"  Assumptions: {len(ass_emergent)}/9 — {ass_emergent}")
    print(f"  Mechanisms:  {len(mech_emergent)}/8 — {mech_emergent}")
    print(f"  Viability basin: {basin}")
    print(f"  PC1: {pca['pc1_pct']}%, PC2: {pca['pc2_pct']}%, Intrinsic dim: {pca['intrinsic_dim']}")
    print(f"  Fertile corridor: {corridor['corridor_detected']} (EoC: {corridor['edge_of_chaos_pct']}%)")
    if pca["intrinsic_dim"] <= 3:
        print(f"  *** LOW-DIMENSIONAL GEOMETRY DETECTED ***")

# ============================================================
# ABLATION ON COMBINED PHASE
# ============================================================

print(f"\n{'='*72}")
print("ABLATION — remove mechanisms from combined phase")
print("=" * 72)

combined_pdef = [p for p in PHASE_DEFS if p["name"] == "combined"][0]
mechanism_keys = ["hierarchy_depth", "resource_limit", "adaptation_rate",
                  "context_sensitivity", "corridor_feedback"]

ablation_results = []
for mech_key in mechanism_keys:
    ablated_params = dict(combined_pdef["mech_params"])
    ablated_params[mech_key] = 0.0  # disable this mechanism
    params_list = [build_params(bp, "combined", ablated_params) for bp in base_params_list]
    results = []
    for params in params_list:
        r = assay_system(params)
        results.append(r)
    pca = run_pca(results)
    corridor = run_corridor_analysis(results)
    ablation_results.append({
        "removed": mech_key,
        "pc1_pct": pca["pc1_pct"],
        "intrinsic_dim": pca["intrinsic_dim"],
        "corridor_detected": corridor["corridor_detected"],
    })
    print(f"  Remove {mech_key}: PC1={pca['pc1_pct']}%, dim={pca['intrinsic_dim']}, "
          f"corridor={corridor['corridor_detected']}")


# ============================================================
# LOADING ANALYSIS — which metrics dominate each PC
# ============================================================

best_phase = max(all_phase_results, key=lambda p: (p["pca"]["pc1_pct"], -p["pca"]["intrinsic_dim"]))
print(f"\n{'='*72}")
print(f"LOADING ANALYSIS — Best phase: {best_phase['label']}")
print(f"  PC1: {best_phase['pca']['pc1_pct']}%, PC2: {best_phase['pca']['pc2_pct']}%")
print(f"  Intrinsic dim: {best_phase['pca']['intrinsic_dim']}")
print(f"\n  {'Metric':<8} {'PC1 loading':<12} {'PC2 loading':<12}")
print(f"  {'-'*32}")
for mn, l1, l2 in zip(best_phase["pca"]["metric_names"],
                       best_phase["pca"]["loadings_pc1"],
                       best_phase["pca"]["loadings_pc2"]):
    print(f"  {mn:<8} {l1:<+12.3f} {l2:<+12.3f}")

# Compare to T078 target pattern
generative_metrics = ["RC", "OE", "SR", "NP", "RD", "G", "S"]
stability_metrics = ["R", "P", "C"]
gen_load = sum(abs(best_phase["pca"]["loadings_pc1"][best_phase["pca"]["metric_names"].index(m)])
               for m in generative_metrics if m in best_phase["pca"]["metric_names"])
gen_load /= len(generative_metrics)
stab_load = sum(abs(best_phase["pca"]["loadings_pc1"][best_phase["pca"]["metric_names"].index(m)])
                for m in stability_metrics if m in best_phase["pca"]["metric_names"])
stab_load /= len(stability_metrics)
print(f"\n  PC1: Generative metrics mean abs loading: {gen_load:.3f}")
print(f"  PC1: Stability metrics mean abs loading:  {stab_load:.3f}")
print(f"  PC1 generative dominance: {'YES' if gen_load > stab_load * 1.2 else 'PARTIAL' if gen_load > stab_load else 'NO'}")


# ============================================================
# OUTPUT SUMMARY
# ============================================================

print(f"\n{'='*72}")
print("SUMMARY TABLE")
print("=" * 72)
print(f"\n  {'Phase':<20} {'N_all':<7} {'Assumptions':<14} {'PC1%':<8} {'PC2%':<8} {'Dim':<5} {'Corridor':<10}")
print(f"  {'-'*72}")
for pr in all_phase_results:
    label_s = pr["label"][:18]
    a = pr["assumptions"]
    p = pr["pca"]
    c = pr["corridor"]
    corr_s = "YES" if c["corridor_detected"] else ("NO" if c["corridor_detected"] is False else "?")
    dim_s = f"{p['intrinsic_dim']}"
    print(f"  {label_s:<20} {pr['n_all']:<7} {a['n_emergent']}/9{'*' if a['n_emergent']>=7 else ' ':<11} "
          f"{p['pc1_pct']:<8} {p['pc2_pct']:<8} {dim_s:<5} {corr_s:<10}")

print(f"\n  Target:                                   ~75.1%   ~17.5%   2     YES")
print(f"  {'-'*72}")

# Ablation summary
print(f"\n  Ablation (from combined):")
print(f"  {'Removed':<25} {'PC1%':<8} {'Dim':<5} {'Corridor':<10}")
print(f"  {'-'*48}")
for ar in ablation_results:
    print(f"  {ar['removed']:<25} {ar['pc1_pct']:<8} {ar['intrinsic_dim']:<5} "
          f"{'YES' if ar['corridor_detected'] else 'NO':<10}")


# ============================================================
# WRITE OUTPUTS
# ============================================================

with open(OUT / "t083_phase_comparison.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["phase", "n_all", "n_none", "assumptions", "mechanisms", "viability_basin",
                 "pc1_pct", "pc2_pct", "pc3_pct", "intrinsic_dim",
                 "corridor_detected", "edge_of_chaos_pct"])
    for pr in all_phase_results:
        p = pr["pca"]
        c = pr["corridor"]
        w.writerow([pr["label"], pr["n_all"], pr["n_none"],
                     pr["assumptions"]["n_emergent"], pr["mechanisms"]["n_emergent"],
                     pr["viability_basin"],
                     p["pc1_pct"], p["pc2_pct"],
                     p["explained"][2] if len(p["explained"]) > 2 else 0,
                     p["intrinsic_dim"],
                     c["corridor_detected"], c["edge_of_chaos_pct"]])

with open(OUT / "t083_loading_analysis.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["metric", "pc1_loading", "pc2_loading"])
    for mn, l1, l2 in zip(best_phase["pca"]["metric_names"],
                          best_phase["pca"]["loadings_pc1"],
                          best_phase["pca"]["loadings_pc2"]):
        w.writerow([mn, l1, l2])

with open(OUT / "t083_ablation.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["removed", "pc1_pct", "intrinsic_dim", "corridor_detected"])
    for ar in ablation_results:
        w.writerow([ar["removed"], ar["pc1_pct"], ar["intrinsic_dim"], ar["corridor_detected"]])

# Full summary JSON
summary = {
    "audit": "T083 — Latent Geometry Audit",
    "target_pc1": TARGET_PC1,
    "target_intrinsic_dim": TARGET_INTRINSIC_DIM,
    "target_pc1_generative_dominance": True,
    "n_systems_per_phase": 300,
    "phases": [],
    "best_phase": best_phase["label"],
    "best_pc1": best_phase["pca"]["pc1_pct"],
    "best_intrinsic_dim": best_phase["pca"]["intrinsic_dim"],
    "ablation": [],
}
for pr in all_phase_results:
    p = pr["pca"]
    c = pr["corridor"]
    summary["phases"].append({
        "label": pr["label"],
        "n_all": pr["n_all"],
        "assumptions_emerged": pr["assumptions"]["n_emergent"],
        "mechanisms_emerged": pr["mechanisms"]["n_emergent"],
        "viability_basin": pr["viability_basin"],
        "pc1_pct": p["pc1_pct"],
        "pc2_pct": p["pc2_pct"],
        "intrinsic_dim": p["intrinsic_dim"],
        "corridor_detected": c["corridor_detected"],
        "edge_of_chaos_pct": c["edge_of_chaos_pct"],
        "explained": p["explained"][:6],
    })
for ar in ablation_results:
    summary["ablation"].append(ar)

with open(OUT / "t083_summary.json", "w") as f:
    json.dump(summary, f, indent=2)

print(f"\nWrote t083_phase_comparison.csv")
print(f"Wrote t083_loading_analysis.csv")
print(f"Wrote t083_ablation.csv")
print(f"Wrote t083_summary.json")
print(f"\nT083 complete.")
