#!/usr/bin/env python3
"""
T089: Background Prevalence Audit
==================================
Question: Are the 9 substrate assumptions genuinely generated by MC2+MC3+MC4,
or are they properties of the simulation substrate itself?

Logic: If assumptions are near-universal in RANDOM systems too, they are
simulator artifacts, not generative products of the MCs. If they are enriched
in MC-satisfying/viable systems relative to random background, they are
genuinely generated by the MCs.

Design:
  1. Generate N_random fully random systems (all params uniform)
  2. Reuse the 240 structured systems from T082/T088
  3. For each population, compute per-assumption prevalence (>= 0.2, >= 0.5)
  4. Compute enrichment over random background
  5. Populations:
     a. Random background
     b. All structured
     c. Non-viable (MC2+MC3+MC4 < 0.5)
     d. MC-satisfying (MC2+MC3+MC4 >= 0.5)
     e. Viable (viability thresholds met)
     f. MC-satisfying AND viable (both)
"""

import csv, json, math, random
from pathlib import Path
from collections import defaultdict
import importlib.util

import numpy as np

OUT = Path("/home/student/sgp_core_v2/sfh_sgp_ood_outputs")
random.seed(42)
np.random.seed(42)

# ============================================================
# IMPORT CORE FRAMEWORK
# ============================================================

spec = importlib.util.spec_from_file_location("t082",
    "/home/student/sgp_core_v2/T082_structural_realization_audit.py")
t082 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(t082)

assay_system = t082.assay_system
ASS_IDS = t082.ASS_IDS
MISSING = ["OC2", "OC1", "CD1", "IS2"]
EMERGENT_BASELINE = ["IC1", "IS1", "CD2", "EC1", "SR1"]

# ============================================================
# GENERATE RANDOM SYSTEMS
# ============================================================

print("=" * 72)
print("T089: BACKGROUND PREVALENCE AUDIT")
print("=" * 72)

N_RANDOM = 1000
print(f"\nGenerating {N_RANDOM} fully random systems...")

random_params = []
for _ in range(N_RANDOM):
    random_params.append({
        "base_n_states": random.choice([3, 4, 5, 6]),
        "determinism": random.uniform(0.2, 0.95),
        "connectivity": random.uniform(0.3, 0.9),
        "novelty_drive": random.uniform(0.1, 0.5),
        "boundary_strength": random.uniform(0.3, 0.9),
        "self_model_level": random.choice([0, 1, 2, 3]),
        "self_model_influence": random.uniform(0.0, 0.6),
    })

random_results = []
for i, params in enumerate(random_params):
    r = assay_system(params)
    random_results.append(r)
    if (i + 1) % 200 == 0:
        print(f"  Ran {i+1}/{N_RANDOM} random systems...")
print(f"  Complete: {len(random_results)} random systems")

# ============================================================
# REUSE STRUCTURED SYSTEMS FROM T082
# ============================================================

print(f"\nRegenerating 240 structured systems (T082 grid)...")
all_params = []
for det in [0.2, 0.4, 0.6, 0.8, 0.95]:
    for conn in [0.3, 0.5, 0.7, 0.9]:
        for sm_level in [0, 1, 2, 3]:
            for sm_inf in [0.0, 0.3, 0.6]:
                all_params.append({
                    "base_n_states": random.choice([3, 4, 5, 6]),
                    "determinism": det,
                    "connectivity": conn,
                    "novelty_drive": random.choice([0.1, 0.2, 0.3, 0.5]),
                    "boundary_strength": random.choice([0.3, 0.5, 0.7, 0.9]),
                    "self_model_level": sm_level,
                    "self_model_influence": sm_inf,
                })
random.shuffle(all_params)
all_params = all_params[:240]

structured_results = []
for i, params in enumerate(all_params):
    r = assay_system(params)
    structured_results.append(r)
    if (i + 1) % 50 == 0:
        print(f"  Ran {i+1}/{len(all_params)} structured systems...")
print(f"  Complete: {len(structured_results)} structured systems")

# ============================================================
# DEFINE POPULATIONS
# ============================================================

def is_mc_satisfying(r):
    return r["mc2"] >= 0.5 and r["mc3"] >= 0.5 and r["mc4"] >= 0.5

def is_viable(r):
    return r["viable"]

populations = {
    "Random background (all)": random_results,
    "Structured (all)": structured_results,
    "Structured — non-viable": [r for r in structured_results if not is_viable(r)],
    "Structured — MC2+MC3+MC4 < 0.5": [r for r in structured_results if not is_mc_satisfying(r)],
    "Structured — MC2+MC3+MC4 >= 0.5": [r for r in structured_results if is_mc_satisfying(r)],
    "Structured — viable": [r for r in structured_results if is_viable(r)],
    "Structured — MC-satisfying + viable": [r for r in structured_results if is_mc_satisfying(r) and is_viable(r)],
}

# ============================================================
# COMPUTE PREVALENCE
# ============================================================

print(f"\n{'='*72}")
print("PREVALENCE BY POPULATION (>= 0.2 threshold)")
print("=" * 72)

threshold = 0.2

header = f"{'Population':<35} {'n':<6} "
for aid in ASS_IDS:
    header += f"{aid:<8} "
print(f"\n{header}")
print(f"{'─'* (35 + 6 + 9 * len(ASS_IDS))}")

prevalence_table = {}
for pop_name, pop_results in populations.items():
    n = len(pop_results)
    pcts = {}
    for aid in ASS_IDS:
        vals = [r["em"][aid] for r in pop_results]
        pct = np.mean([v >= threshold for v in vals]) * 100
        pcts[aid] = pct
    prevalence_table[pop_name] = pcts

    row = f"{pop_name:<35} {n:<6} "
    for aid in ASS_IDS:
        row += f"{pcts[aid]:<8.1f} "
    print(row)

# Also at >= 0.5 threshold
print(f"\n{'='*72}")
print("PREVALENCE BY POPULATION (>= 0.5 threshold)")
print("=" * 72)

header = f"{'Population':<35} {'n':<6} "
for aid in ASS_IDS:
    header += f"{aid:<8} "
print(f"\n{header}")
print(f"{'─'* (35 + 6 + 9 * len(ASS_IDS))}")

for pop_name, pop_results in populations.items():
    n = len(pop_results)
    row = f"{pop_name:<35} {n:<6} "
    for aid in ASS_IDS:
        vals = [r["em"][aid] for r in pop_results]
        pct = np.mean([v >= 0.5 for v in vals]) * 100
        row += f"{pct:<8.1f} "
    print(row)

# ============================================================
# ENRICHMENT OVER RANDOM BACKGROUND
# ============================================================

print(f"\n{'='*72}")
print("ENRICHMENT OVER RANDOM BACKGROUND (>= 0.2)")
print("Enrichment = prevalence_in_group / prevalence_in_random_background")
print("Enrichment > 1 means group has higher prevalence than random")
print("=" * 72)

random_pcts = prevalence_table["Random background (all)"]

header = f"{'Population':<35} "
for aid in ASS_IDS:
    header += f"{aid:<8} "
print(f"\n{header}")
print(f"{'─'* (35 + 9 * len(ASS_IDS))}")

for pop_name in prevalence_table:
    if pop_name == "Random background (all)":
        continue
    pcts = prevalence_table[pop_name]
    row = f"{pop_name:<35} "
    for aid in ASS_IDS:
        if random_pcts[aid] > 0:
            enrich = pcts[aid] / random_pcts[aid]
        else:
            enrich = float('inf')
        row += f"{enrich:<8.3f} "
    print(row)

# ============================================================
# MEAN VALUES BY POPULATION
# ============================================================

print(f"\n{'='*72}")
print("MEAN ASSUMPTION VALUES BY POPULATION")
print("=" * 72)

header = f"{'Population':<35} {'n':<6} "
for aid in ASS_IDS:
    header += f"{aid:<8} "
print(f"\n{header}")
print(f"{'─'* (35 + 6 + 9 * len(ASS_IDS))}")

for pop_name, pop_results in populations.items():
    n = len(pop_results)
    row = f"{pop_name:<35} {n:<6} "
    for aid in ASS_IDS:
        vals = [r["em"][aid] for r in pop_results]
        row += f"{np.mean(vals):<8.3f} "
    print(row)

# ============================================================
# MEAN MC SCORES BY POPULATION
# ============================================================

print(f"\n{'='*72}")
print("MEAN MC SCORES BY POPULATION")
print("=" * 72)

mc_names = ["mc2", "mc3", "mc4", "mc5", "mc1", "sp"]
header = f"{'Population':<35} {'n':<6} "
for mn in mc_names:
    header += f"{mn:<8} "
print(f"\n{header}")
print(f"{'─'* (35 + 6 + 9 * len(mc_names))}")

for pop_name, pop_results in populations.items():
    n = len(pop_results)
    row = f"{pop_name:<35} {n:<6} "
    for mn in mc_names:
        vals = [r[mn] for r in pop_results]
        row += f"{np.mean(vals):<8.3f} "
    print(row)

# ============================================================
# ENRICHMENT AT THE VIABLE SUBPOPULATION LEVEL
# ============================================================

print(f"\n{'='*72}")
print("ENRICHMENT: VIABLE + MC-SATISFYING vs VIABLE ALONE vs NON-VIABLE")
print("= Does satisfying MCs add anything beyond what viability already gives?")
print("=" * 72)

# Split structured into viable subgroups by MC status
viable_mc_sat = [r for r in structured_results if is_viable(r) and is_mc_satisfying(r)]
viable_not_mc = [r for r in structured_results if is_viable(r) and not is_mc_satisfying(r)]
nonviable_mc_sat = [r for r in structured_results if not is_viable(r) and is_mc_satisfying(r)]
nonviable_not_mc = [r for r in structured_results if not is_viable(r) and not is_mc_satisfying(r)]

subgroups = {
    "Viable + MC-sat": viable_mc_sat,
    "Viable + NOT MC-sat": viable_not_mc,
    "Non-viable + MC-sat": nonviable_mc_sat,
    "Non-viable + NOT MC-sat": nonviable_not_mc,
}

print(f"\n{'Subgroup':<25} {'n':<6} ", end="")
for aid in ASS_IDS:
    print(f"{aid:<8} ", end="")
print()
print(f"{'─'* (25 + 6 + 9 * len(ASS_IDS))}")

for sg_name, sg_results in subgroups.items():
    n = len(sg_results)
    if n == 0:
        print(f"{sg_name:<25} {n:<6}  (empty)")
        continue
    row = f"{sg_name:<25} {n:<6} "
    for aid in ASS_IDS:
        vals = [r["em"][aid] for r in sg_results]
        pct = np.mean([v >= 0.2 for v in vals]) * 100
        row += f"{pct:<8.1f} "
    print(row)

# ============================================================
# ENRICHMENT: per-assumption random vs structured distributions
# ============================================================

print(f"\n{'='*72}")
print("KOLMOGOROV-SMIRNOV TEST: Random vs Structured")
print("= Are the distributions different?")
print("=" * 72)

from scipy.stats import ks_2samp

print(f"\n{'Assumption':<8} {'KS statistic':<14} {'p-value':<10} {'Different?':<10}")
print(f"{'─'*42}")
for aid in ASS_IDS:
    random_vals = [r["em"][aid] for r in random_results]
    struct_vals = [r["em"][aid] for r in structured_results]
    stat, pval = ks_2samp(random_vals, struct_vals)
    print(f"{aid:<8} {stat:<14.4f} {pval:<10.6f} {'YES' if pval < 0.05 else 'no':<10}")

# ============================================================
# FINAL CLASSIFICATION
# ============================================================

print(f"\n{'='*72}")
print("FINAL CLASSIFICATION")
print("=" * 72)

for aid in ASS_IDS:
    random_pct = prevalence_table["Random background (all)"][aid]
    mc_sat_pct = prevalence_table["Structured — MC2+MC3+MC4 >= 0.5"][aid]
    viable_pct = prevalence_table["Structured — viable"][aid]
    rand_mean = np.mean([r["em"][aid] for r in random_results])
    struct_mean = np.mean([r["em"][aid] for r in structured_results])
    mc_sat_mean = np.mean([r["em"][aid] for r in populations["Structured — MC2+MC3+MC4 >= 0.5"]])
    viable_mean = np.mean([r["em"][aid] for r in populations["Structured — viable"]])

    # Enrichment calculations
    enrich_mc = mc_sat_pct / random_pct if random_pct > 0 else float('inf')
    enrich_viable = viable_pct / random_pct if random_pct > 0 else float('inf')

    print(f"\n  {'─'*60}")
    print(f"  {aid}:")
    print(f"    Random background: mean={rand_mean:.3f}, >=0.2={random_pct:.1f}%")
    print(f"    Structured (all):  mean={struct_mean:.3f}, >=0.2={prevalence_table['Structured (all)'][aid]:.1f}%")
    print(f"    MC-satisfying:     mean={mc_sat_mean:.3f}, >=0.2={mc_sat_pct:.1f}% (enrich={enrich_mc:.3f}x)")
    print(f"    Viable:            mean={viable_mean:.3f}, >=0.2={viable_pct:.1f}% (enrich={enrich_viable:.3f}x)")

    if enrich_mc < 1.1:
        print(f"    >>> VERDICT: SIMULATOR ARTIFACT — assumption prevalence in MC-satisfying")
        print(f"        systems is indistinguishable from random background")
    elif enrich_mc < 1.3:
        print(f"    >>> VERDICT: WEAKLY GENERATED — modest enrichment over random background")
    else:
        print(f"    >>> VERDICT: GENERATED BY MCs — clear enrichment over random background")

    # Additional: does viability add anything beyond MC satisfaction?
    if mc_sat_pct < 99 and viable_pct > mc_sat_pct:
        print(f"        NOTE: viability adds additional enrichment beyond MC satisfaction alone")

# ============================================================
# WRITE OUTPUTS
# ============================================================

# Prevalence table (>= 0.2 and >= 0.5)
with open(OUT / "t089_prevalence.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["population", "n", "threshold"] + ASS_IDS)
    for thresh in [0.2, 0.5]:
        for pop_name, pop_results in populations.items():
            n = len(pop_results)
            row = [pop_name, n, thresh]
            for aid in ASS_IDS:
                vals = [r["em"][aid] for r in pop_results]
                pct = np.mean([v >= thresh for v in vals]) * 100
                row.append(round(pct, 1))
            w.writerow(row)

# Enrichment table
with open(OUT / "t089_enrichment.csv", "w", newline="") as f:
    w = csv.writer(f)
    random_pcts = prevalence_table["Random background (all)"]
    w.writerow(["population"] + ASS_IDS)
    for pop_name in prevalence_table:
        if pop_name == "Random background (all)":
            continue
        pcts = prevalence_table[pop_name]
        row = [pop_name]
        for aid in ASS_IDS:
            if random_pcts[aid] > 0:
                enrich = pcts[aid] / random_pcts[aid]
            else:
                enrich = float('inf')
            row.append(round(enrich, 3))
        w.writerow(row)

# Mean values table
with open(OUT / "t089_means.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["population", "n"] + ASS_IDS)
    for pop_name, pop_results in populations.items():
        n = len(pop_results)
        row = [pop_name, n]
        for aid in ASS_IDS:
            vals = [r["em"][aid] for r in pop_results]
            row.append(round(np.mean(vals), 3))
        w.writerow(row)

# Subgroup breakdown
with open(OUT / "t089_subgroups.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["subgroup", "n"] + ASS_IDS)
    for sg_name, sg_results in subgroups.items():
        n = len(sg_results)
        if n == 0:
            w.writerow([sg_name, 0] + [""] * len(ASS_IDS))
            continue
        row = [sg_name, n]
        for aid in ASS_IDS:
            vals = [r["em"][aid] for r in sg_results]
            pct = np.mean([v >= 0.2 for v in vals]) * 100
            row.append(round(pct, 1))
        w.writerow(row)

# Summary JSON
summary = {
    "audit": "T089 — Background Prevalence Audit",
    "objective": "Determine whether 9 substrate assumptions are generated by MCs or are simulator artifacts",
    "n_random": int(len(random_results)),
    "n_structured": int(len(structured_results)),
    "populations": {
        pop_name: int(len(pop_results))
        for pop_name, pop_results in populations.items()
    },
    "prevalence_at_02": {},
    "prevalence_at_05": {},
    "verdicts": {},
}

for pop_name, pop_results in populations.items():
    n = len(pop_results)
    prev_02 = {}
    prev_05 = {}
    for aid in ASS_IDS:
        vals = [r["em"][aid] for r in pop_results]
        prev_02[aid] = round(float(np.mean([v >= 0.2 for v in vals]) * 100), 1)
        prev_05[aid] = round(float(np.mean([v >= 0.5 for v in vals]) * 100), 1)
    summary["prevalence_at_02"][pop_name] = prev_02
    summary["prevalence_at_05"][pop_name] = prev_05

for aid in ASS_IDS:
    random_pct = summary["prevalence_at_02"]["Random background (all)"][aid]
    mc_sat_pct = summary["prevalence_at_02"]["Structured — MC2+MC3+MC4 >= 0.5"][aid]
    viable_pct = summary["prevalence_at_02"]["Structured — viable"][aid]
    enrich_mc = round(mc_sat_pct / random_pct, 3) if random_pct > 0 else None
    enrich_viable = round(viable_pct / random_pct, 3) if random_pct > 0 else None

    if enrich_mc is None or enrich_mc < 1.1:
        verdict = "simulator_artifact"
    elif enrich_mc < 1.3:
        verdict = "weakly_generated"
    else:
        verdict = "generated_by_MCs"

    summary["verdicts"][aid] = {
        "random_prevalence_02": random_pct,
        "mc_satisfying_prevalence_02": mc_sat_pct,
        "viable_prevalence_02": viable_pct,
        "enrichment_over_random": enrich_mc,
        "enrichment_viable_over_random": enrich_viable,
        "verdict": verdict,
    }

with open(OUT / "t089_summary.json", "w") as f:
    json.dump(summary, f, indent=2)

print(f"\nWrote t089_prevalence.csv")
print(f"Wrote t089_enrichment.csv")
print(f"Wrote t089_means.csv")
print(f"Wrote t089_subgroups.csv")
print(f"Wrote t089_summary.json")
print(f"\nT089 complete.")
